services:
  yeti-test-vps:
    build:
      context: .
      dockerfile: Dockerfile
    image: server-test-vps
    container_name: yeti-test-vps
    ports:
      - "2222:22"
      - "8080:8080"
    volumes:
      - ./config/yeti-server-config.json:/opt/yeti-server/yeti-server-config.json
    restart: unless-stopped